services:

  backend:
    image: ghcr.io/optivem/atdd-accelerator-template-multi-comp/backend:latest
    ports:
      - "8080:8080"
    environment:
      - TODOS_API_HOST=https://jsonplaceholder.typicode.com
    networks:
      - app-network

  frontend:
    image: ghcr.io/optivem/atdd-accelerator-template-multi-comp/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge